import { TerminologySkins } from "~/types/terminology";

export const terminologySkins: TerminologySkins = {
	default: {
		organization: 'organization',
		treasury: 'treasury',
		escrow: 'escrow',
		task: 'task',
		contributor: 'contributor',
		contributionManager: 'contribution manager',
		treasuryOwner: 'treasury owner',
		taskStatus: 'status',
		prerequisite: 'prerequisite',
		credential: 'credential',
		acceptanceCriteria: 'acceptance criteria',
	},
	leadGen: {
		organization: 'leadgen-organization',
		treasury: 'leadgen-organization',
		escrow: 'leadgen-project',
		task: 'leadgen-task',
		contributor: 'leadgen-contributor',
		contributionManager: 'leadgen-organizer',
		treasuryOwner: 'leadgen-treasury-owner',
		taskStatus: 'leadgen-progress',
		prerequisite: 'leadgen-prerequisite',
		credential: 'leadgen-credential',
		acceptanceCriteria: 'leadgen-acceptanceCriteria',
	},
	validatorNames: {
		organization: 'organization',
		treasury: 'treasury',
		escrow: 'escrow',
		task: 'task',
		contributor: 'contributor',
		contributionManager: 'contribution manager',
		treasuryOwner: 'treasury owner',
		taskStatus: 'status',
		prerequisite: 'prerequisite',
		credential: 'credential',
		acceptanceCriteria: 'acceptanceCriteria',
	},
	mvpTestTerms: {
		organization: 'organization',
		treasury: 'project',
		escrow: 'project',
		task: 'task',
		contributor: 'contributor',
		contributionManager: 'organizer',
		treasuryOwner: 'treasury owner',
		taskStatus: 'status',
		prerequisite: 'credential',
		credential: 'credential',
		acceptanceCriteria: 'acceptance criteria',
	},
	s3: {
		organization: 'organization',
		treasury: 'circle',
		escrow: 'backlog',
		task: 'task',
		contributor: 'contributor',
		contributionManager: 'facilitator',
		treasuryOwner: 'treasury owner',
		taskStatus: 'status',
		prerequisite: 'role',
		credential: 'role',
		acceptanceCriteria: 'evaluation criteria',
	},
} as const;
